First draft of fs2 backend: a rebase
This is a giant squash.  Perhaps the squash will help make the
merge to 'develop' less painful.
The commits involved were from e05859324..8720e3124

Fix unit tests

Fix bucket naming scheme in chash_cs_keyfun()

WIP: Friday evening

WIP: put_object() and get_object() refactored, all t* tests working, yay

Answer the S3 bucket name & S3 object name lenght limit question

WIP

WIP: fixes for testing, new capability + vnode testing

WIP: tombstone

WIP: fix simple_test_(), relies on riak_kv branch 'slf-backend-capability-enc+no_get'

WIP: more test fixes, relies on riak_kv branch 'slf-backend-capability-enc+no_get'

Fix non-test compilation errors

Fix naive implementation of is_empty(), add t5 test

Fix folding over tombstoned things: tombstones shouldn't be hidden, silly

Remove unused eqc_filter_list_keys/2

Add fake vclock to tombstone, fix EQC test error and spamminess

Add get_object/4 and put_object/5 to riak_cs_kv_multi_backend.erl

Damn HFS+, part I: use setuid bit instead of setgid

Move from modified-base64 encoded paths -> hexadecimal ASCII representation

The switch to hex+ASCII removes a testing annoyance on OS X:
the HFS+ file system is usually configured to be case preserving
but not case sensitive.  The use of both upper- & lowercase letters
by the modified-base64 (base64fs2.erl) can cause false conflicts.

I put the hexlist_to_binary/1 and binary_to_hexlist/2 functions
in the riak_kv_fs2_backend.erl module (where they don't really belong)
to avoid a module dependency when running EUnit & QuickCheck tests
for riak_kv_fs2_backend, which need to be run from the riak_kv source
repo.  There's still a dependency on include/riak_cs_lfs.hrl, which
needs fixing, but at least it's only one dep instead of two.

Add bucket prefix length, TYPICAL_BUCKET_PREFIX_LEN, et al.

Add missing (duh) file version header bytes

Avoid unconditional clobber of file header on each block put

Name each of the EQC tests

Remove out-of-order trailer

Add callback so backend_eqc test can deal with fold_keys() returning
more keys than actually written: e.g. put block # 3 will result in
fold_keys() believing that blocks #0, 1, and 2 will also exist.
If you try to fetch 0 or 1 or 2, you'll get not_found, which would
be correct of course.  But fold_keys() is optimized for speed and
not for 100% correctness -- fold_objects() and get() are correct.

Add get sibling resolution & app read repair

Refactor sibling resolution, part I

Several refactorings:

* Change riak_cs_block_server to do proper remote retries (when available)
  in {get_block, ...} cases.  Includes exponential backoff.

* Add block_get_retry statistic.

* Change sibling resolution to be more correct and to prepare it for
  relocation to the riak_kv_fs2_backend.erl module.

* Use ?MD_DELETED where feasible.

Move resolv_robj_siblings/1 to riak_kv_fs2_backend, to fix handoff problem

I noticed that handoff kept failing due to an error on the receiving
vnode (which caused "... failed because of error:{badmatch,{error,closed}} ..."
messages on the sending side).  The problem was caused by siblings in
the fs2's put_object() func, where one of the siblings was a tombstone.

resolv_robj_siblings/1 is the function that can figure that kind of
situation out correctly, so I moved it to the fs2 backend to try to
minimize external Riak-CS-related module dependencies.

Draft: n_val + sloppy_quorum on 1st try, then retry standard

Refactor all MD5-related functions

Use master barnch of riak-erlang-client, pin it later

Change riak_cs_utils:md5 to accept binary or string input

Adjustments for functions that have moved from riak_cs_utils to riak_cs_config

Add support for async drop()

Automatically add fudge factor for max object size

Misc tiny cleanup

Add dict:find() key not present workaround

Replace 'file' calls to file_server_2 -> Folgers Crystals

Introduce v0, v1, v2 bclasses, and object size-based control over bclass use

Added the bclass to the ?MANIFEST.props list to avoid making a
change to the ?MANIFEST record to accomodate the new metadata.

Also, fix riak_cs_get_fsm_eqc test

Add missing arg to Retry fun in riak_cs_block_server:do_get_block

WIP: conversion to i_depth=3

WIP: fold_lowlevel() working, other folds broken

WIP: fold_lowlevel() minor deuglification

WIP: add upper_db to put_object()

WIP: add upper_db to delete()

WIP: fold_buckets() on upper_db

WIP: fold_keys() on upper_db

WIP: fold_objects() over fs2 data, fixed

Add async fold capability to all 3 folds

Add bucket filter to fold_keys

Add inefficient bucket filter to fold_lower_level()

Add comprehensive to fold_objects() implementation

Add 'aae_reconstruction' option to fold_objects()